#!/bin/bash

##########
# Don't push to main / master
##########
protected_branch_1='main'
protected_branch_2='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch_1 = $current_branch ] || [ $protected_branch_2 = $current_branch ]
then
    read -p "You're about to push main / master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi

