# Ruby Dev
alias b="bundle --jobs 4"
alias be="bundle exec"

# Bash
alias bash_refresh="source ~/.bash_profile"

# Git
alias g="git"
alias gd="git diff --color | diff-so-fancy  | less --tabs=4 -RFX"
alias gsco="stash_and_checkout"
alias grebasesafe="git fetch --tags && git rebase last-successful-build"
alias gg="git grep"
# alias ga="git add"
# alias gaa="git add --all"
# alias gco="git checkout"
# alias gcom="git checkout master"
# alias gcmm="git commit --verbose"
# alias gl="git log --pretty=format:'%Cred%h%Creset @ %Cgreen%cr%Creset: %s %C(bold)%d%Creset %C(bold blue)<%an>%Creset' --abbrev-commit"
# alias gpom="git pull origin master"
# alias gsh="git show --name-only"
# alias gst="git status -sb"
# alias rug="git stash"

# System
alias cc="clear"
alias ll="ls -l"
alias all="ls -al"

# Directory Navigation
alias ..="cd .."
alias ...="cd ../.."
alias dot="cd ~/dotfiles"
alias dev="cd ~/dev"
alias misc="cd ~/misc"

