# Ruby Dev
alias b="bundle"
alias be="bundle exec"

# Git
alias g="git"
alias ga="git add"
alias gaa="git add --all"
alias gco="git checkout"
alias gcom="git checkout master"
alias gcmm="git commit"
alias gd="git diff --color | diff-so-fancy  | less --tabs=4 -RFX"
alias gg="git grep"
alias gl="git log --pretty=format:'%Cred%h%Creset @ %Cgreen%cr%Creset: %s %C(bold)%d%Creset %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gpom="git pull origin master"
alias gsh="git show --name-only"
alias gst="git status -sb"
alias rug="git stash"


# System
alias cc="clear"
alias ll="ls -l"
alias all="ls -al"

# Directory Navigation
alias ..="cd .."
alias ...="cd ../.."
alias dot="cd ~/dotfiles"
alias dev="cd ~/dev"
