export EDITOR='vim'

# Ruby Dev
alias b="bundle"
alias be="bundle exec"
alias bi="bundle install"

# Git
alias g="git"
alias gg="git grep"
alias gl="git log --pretty=format:'%Cred%h%Creset @ %Cgreen%cr%Creset: %f %C(bold)%d%Creset %C(bold blue)<%an>%Creset' --abbrev-commit"

# System
alias cc="clear"
alias ll="ls -l"
alias all="ls -al"

# Directory Navigation
alias ..="cd .."
alias ...="cd ../.."
alias dot="cd ~/dotfiles"
alias dev="cd ~/dev"
